(defun sqr (a b)
  (values (* a a)
          (* b b)))

(defmacro foo (a b)
  (let ((x (gensym))
        (y (gensym)))
    `((multiple-value-bind (,x ,y) ,(sqr a b)
        (format t "f1: ~a ~a~%" ,x ,y)
        ,(format t "f2: ~a ~a~%" x y)
        )
      (multiple-value-bind (,x ,y) (sqr ,a ,b)
        (format t "f1: ~a ~a~%" ,x ,y)
        ,(format t "f2: ~a ~a~%" x y)
        ))))
